# Generated by Django 5.0.3 on 2024-03-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventgenre_remove_event_created_by_and_more'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('twitter_template', models.JSONField(blank=True, null=True)),
                ('discord_template', models.JSONField(blank=True, null=True)),
                ('vrchat_template', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='googlecalendarevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='event',
        ),
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField()),
                ('posted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.announcementtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('access_token_secret', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnouncementStatus',
        ),
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.DeleteModel(
            name='GoogleCalendarEvent',
        ),
        migrations.DeleteModel(
            name='SocialMediaPost',
        ),
    ]
