# Generated by Django 5.0.3 on 2024-03-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_calender_genre', models.CharField(blank=True, choices=[('avatar_fitting', 'アバター試着会'), ('avatar_modification', '改変アバター交流会'), ('other_social', 'その他交流会'), ('vr_drinking', 'VR飲み会'), ('store_event', '店舗系イベント'), ('music_event', '音楽系イベント'), ('academic_event', '学術系イベント'), ('role_playing', 'ロールプレイ'), ('beginner_event', '初心者向けイベント'), ('regular_event', '定期イベント')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='platform_compatibility',
            field=models.CharField(choices=[('pc', 'PCオンリー'), ('pc_android', 'PC/Android両対応（Android対応）'), ('android', 'Android オンリー')], default='pc', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='role',
            field=models.CharField(choices=[('organizer', '主催者'), ('staff', 'スタッフ')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('NONE', '設定なし'), ('CUSTOM', 'カスタム'), ('DAILY', '毎日'), ('WEEKLY', '毎週'), ('BIWEEKLY', '隔週'), ('MONTHLY', '毎月'), ('YEARLY', '毎年')], default='NONE', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, null=True)),
                ('month_day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('occurrence', models.IntegerField(blank=True, choices=[(1, '第1'), (2, '第2'), (3, '第3'), (4, '第4'), (-1, '最終')], null=True)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], null=True)),
                ('custom_dates', models.JSONField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='event.event')),
            ],
        ),
    ]
